from .constraint_parser import Parser

if __name__ == "__main__":
    p = Parser()
    test_cases = [
        "이름은 영어로, 주소는 한국어로 3개",
        "여자 이름만",
        "40세 미만",
        "Gmail만",
        "주소는 한국어로, 이름은 영어로 3개",
        "email은 gmail만, 20세 미만",
        "없는타입",
        "이름, 없는조건",
        "비밀번호 8자 이상, 대문자 1개, 숫자 1개 2개",
        "paragraphs at least 2, no more than 4",
        "phone, gmail only, number over 10",
        "Generate 10 users with Gmail emails under 40 years old",
        "Create 5 samples, full name, email address only gmail, age over 20",
        "10 users, phone number, at least 2 paragraphs, no more than 5 paragraphs",
        "Generate 3 avatars, company, city, country",
        "fullname 2개, email address, under 30",
        "avatar size 50x50 format png",
        "state: California, country: United States",
        "datetime from 2024-01-01 to 2024-12-31 format yyyy-mm-dd",
        "time from 9am to 6pm 24 hour",
        "url protocol host path query",
        "credit card number Visa",
        "credit card type Mastercard",
        "latitude, longitude, product price, swift bic, iban",
        "카드번호 blank 10%",
        "이름 빈 값 15%",
        "전화번호 빈값 20%",
        "이메일 null 25%",
        "주소 nullable 30%",
        "credit card number blank 40%",
        "phone number null 50%",
        "password missing 60%",
        "avatar blank: 70%",
        "state nullable: 80%",
        "10개 중에 3개 빈값 이름",
        "3 out of 10 null phone number",
        "email address blank 0%",
        "비밀번호 8자 이상 대문자 1개, 소문자 1개, 숫자 1개, 기호 1개 blank 25%",
        "국제 전화는 +1 234 567 8901 형식",
        "구분자 없이 숫자만 연속으로",
        "전화번호는 1234567890 으로 작성",
        "아바타 이미지는 128x128 PNG 형식으로 저장해 주세요.",
        "PNG로 저장하고, 혹시 안되면 JPG로 바꿔주세요.",
        "가로 0세로 0, BMP 형식으로 주세요.",
        "가로 0, 세로 0, BMP 형식으로 주세요.",
        "사이즈 512x512, JPEG로 저장 바랍니다.",
        "JPG나 BMP 중 편한 거 쓰세요.",
        "state: California, New York and Ontario",
        "캘리포니아와 도쿄, 뉴욕만",
        "only Bavaria (Bayern), São Paulo, Moscow",
        "state: Île-de-France / Beijing 및 Madrid",
        "state: California, Neverland, Ontario",
        "California, Neverland, Ontario",
        "2023-01-01부터 2023-12-31까지, 형식은 yyyy-mm-dd",
        "시작일 2023-01-01, 종료일 2023-12-31",
        "from 2023-01-01 to 2023-12-31, format mm/dd/yyyy",
        "from 2023-01-01 until 2023-12-31",
        "시작 날짜: 2023/01/01, end date: 2023-12-31, 포맷은 dd/mm/yyyy",
        "from 2023-01-01 to 2023-12-31, format d/m/yyyy",
        "형식 2024/02/02",
        "포맷 yyyy-mm-dd",
        "년월일 포맷",
        "year-month-day format",
        "주문 날짜(order_date)는 2025-02-01 ~ 2025-11-31 사이여야 해.",
        "비밀번호는 최소 10자 이상이고 숫자와 특수 문자가 포함되어야 해",
        "나이는 20 이상 60 이하, 소수점 1자리, nullable 10%",
        "between 3 and 7, up to 2 decimals, nullable 15%",
        "5 초과 10 미만, 정수만",
        "exactly 3, decimals 3",
        "나이 120 이하",
    ]
    for t in test_cases:
        print("입력:", t)
        print(p.parse_field_constraint(t))
        print("-" * 40)
