# 한/영 필드·값 매핑

KOR_TO_ENG_FIELD = {
    # korean_full_name
    "전체 이름": "korean_full_name", "이름 전체": "korean_full_name", "성명": "korean_full_name",
    "풀네임": "korean_full_name", "전성 이름": "korean_full_name", "이름": "korean_full_name",
    "이름 전부": "korean_full_name", "이름 풀": "korean_full_name", "이름(전체)": "korean_full_name",
    "이름(풀)": "korean_full_name", "이름 전체명": "korean_full_name", "이름 풀네임": "korean_full_name",
    "최씨 이름": "korean_full_name", "김씨 이름": "korean_full_name", "이씨 이름": "korean_full_name", "박씨 이름": "korean_full_name",
    "성을 가진 사람": "korean_full_name", "성씨를 가진 사람": "korean_full_name", "성씨가 있는 사람": "korean_full_name",
    "정씨만": "korean_last_name", "강씨만": "korean_last_name", "조씨만": "korean_last_name", "윤씨만": "korean_last_name",
         # korean_last_name - 모든 성씨 관련 패턴을 korean_full_name으로 변경
     "성": "korean_full_name", "성씨": "korean_full_name", "이씨": "korean_full_name", "김씨": "korean_full_name",
     "박씨": "korean_full_name", "최씨": "korean_full_name", "이 성": "korean_full_name", "김 성": "korean_full_name",
     "박 성": "korean_full_name", "최 성": "korean_full_name", "성(이)": "korean_full_name", "성(김)": "korean_full_name",
     "성(박)": "korean_full_name", "성(최)": "korean_full_name",
     # 한국어 전용 표현 (성씨 + 조사/형태소 변형 조합) - korean_full_name으로 변경
     "성이 인 사람": "korean_full_name", "성씨가 인 사람": "korean_full_name", "씨인 사람": "korean_full_name",
     "씨 인 사람": "korean_full_name", "성을 가진 사람": "korean_full_name", "성씨를 가진 사람": "korean_full_name",
           "씨만": "korean_full_name", "성씨만": "korean_full_name", "씨면": "korean_full_name", "씨 성을 가진 사람": "korean_full_name",
     "성(姓)이 인 사람": "korean_full_name",
     "으로 시작하는 사람": "korean_full_name", "로 시작하는 사람": "korean_full_name",
     "성을 쓰는 사람": "korean_full_name", "성씨를 쓰는 사람": "korean_full_name",
     "임": "korean_full_name", "으로 되어 있는 사람": "korean_full_name", "라는 사람": "korean_full_name",
     "이신 분": "korean_full_name", "이신 사람": "korean_full_name", "로 끝나는 사람": "korean_full_name",
     # 한국어 + 영어 혼합 표현
     "last name:": "korean_full_name", "family name:": "korean_full_name",
     "full name starts with": "korean_full_name", "full name begins with": "korean_full_name",

    # korean_first_name
    "이름(이)": "korean_first_name", "이름(김)": "korean_first_name", "이름(박)": "korean_first_name",
    "이름(최)": "korean_first_name", "이름만": "korean_first_name", "이름(한글)": "korean_first_name",
    "이름(영문)": "korean_first_name",
    # korean_address
    "주소": "korean_address", "전체 주소": "korean_address", "집 주소": "korean_address", "거주지": "korean_address",
    "거주 주소": "korean_address", "거주지 주소": "korean_address", "거주지 전체": "korean_address",
    "mail address": "email_address", "email address": "email_address",
    # korean_street_address
    "도로명 주소": "korean_street_address", "도로 주소": "korean_street_address", "도로명": "korean_street_address",
    "도로 전체": "korean_street_address", "도로명 전체": "korean_street_address", "도로명주소": "korean_street_address",
    # korean_city
    "도시": "korean_city", "도시 이름": "korean_city", "사는 도시": "korean_city", "거주 도시": "korean_city",
    "시": "korean_city", "시 이름": "korean_city", "도시 이름(한글)": "korean_city",
    # korean_state
    "시도": "korean_state", "도": "korean_state",     "시/도": "korean_state", "시 도": "korean_state",
    "도 이름": "korean_state", "시 이름": "korean_state",
    # 지원되는 state 이름들 직접 매핑
    "California": "state", "New York": "state", "Seoul": "state", 
    "Île-de-France": "state", "Tokyo": "state", "Beijing": "state", 
    "Ontario": "state", "Bavaria (Bayern)": "state", "São Paulo": "state", 
    "Maharashtra": "state", "Istanbul": "state", "England": "state", 
    "Madrid": "state", "New South Wales": "state", "Moscow": "state",
    # korean_country
    "국가": "korean_country", "나라": "korean_country", "거주 국가": "korean_country", "사는 나라": "korean_country",
    # 지원되는 country 이름들 직접 매핑  
    "United States": "country", "China": "country", "Germany": "country", 
    "United Kingdom": "country", "France": "country", "Japan": "country",
    "India": "country", "Russia": "country", "South Korea": "country", 
    "Brazil": "country", "Canada": "country", "Italy": "country", 
    "Australia": "country", "Spain": "country", "Turkey": "country",
    "미국": "country", "중국": "country", "독일": "country", "영국": "country",
    "프랑스": "country", "일본": "country", "인도": "country", "러시아": "country",
    "대한민국": "country", "한국": "country", "브라질": "country", "캐나다": "country",
    "이탈리아": "country", "호주": "country", "스페인": "country", "튀르키예": "country",
    # korean_postal_code
    "우편번호": "korean_postal_code", "우편 코드": "korean_postal_code", "우편 번호": "korean_postal_code", "우편코드": "korean_postal_code",
    # korean_phone
    "전화번호": "korean_phone", "휴대폰 번호": "korean_phone", "핸드폰 번호": "korean_phone", "연락처": "korean_phone",
    "휴대폰": "korean_phone", "핸드폰": "korean_phone", "전화": "korean_phone",
    # korean_company_name
    "회사명": "korean_company_name", "회사 이름": "korean_company_name", "근무처": "korean_company_name", "근무 회사": "korean_company_name",
    # korean_job_title
    "직책": "korean_job_title", "직위": "korean_job_title", "포지션": "korean_job_title", "직무": "korean_job_title",
    # korean_department_corporate
    "부서": "korean_department_corporate", "소속": "korean_department_corporate", "소속 부서": "korean_department_corporate", "소속팀": "korean_department_corporate",
    # korean_product_name
    "제품명": "korean_product_name", "상품명": "korean_product_name", "제품 이름": "korean_product_name", "상품 이름": "korean_product_name",
    # korean_product_category
    "제품 카테고리": "korean_product_category", "상품 카테고리": "korean_product_category", "제품 종류": "korean_product_category", "상품 종류": "korean_product_category",
    # korean_catch_phrase
    "캐치프레이즈": "korean_catch_phrase", "슬로건": "korean_catch_phrase", "표어": "korean_catch_phrase",
    # korean_product_description
    "제품 설명": "korean_product_description", "상품 설명": "korean_product_description", "제품 소개": "korean_product_description", "상품 소개": "korean_product_description",
    # korean_language
    "언어": "korean_language", "사용 언어": "korean_language", "쓰는 언어": "korean_language",
    # korean_color
    "색상": "korean_color", "컬러": "korean_color", "색": "korean_color",
    # 공통
    "사용자명": "username", "유저명": "username", "계정명": "username", "계정 이름": "username", "유저 이름": "username",
    "비밀번호": "password", "패스워드": "password", "비번": "password",
    "특수문자": "password", "특수 문자": "password", "특수기호": "password", "특수 기호": "password",
    "이메일": "email_address", "이메일 주소": "email_address", "메일": "email_address", "메일 주소": "email_address",
    "네이버 도메인 이메일": "email_address", "네이버 도메인 메일": "email_address", "네이버 도메인 mail": "email_address",
    "구글 도메인 이메일": "email_address", "구글 도메인 메일": "email_address", "구글 도메인 mail": "email_address",
    "지메일 도메인 이메일": "email_address", "지메일 도메인 메일": "email_address", "지메일 도메인 mail": "email_address",
    "야후 도메인 이메일": "email_address", "야후 도메인 메일": "email_address", "야후 도메인 mail": "email_address",
    "핫메일 도메인 이메일": "email_address", "핫메일 도메인 메일": "email_address", "핫메일 도메인 mail": "email_address",
    "아웃룩 도메인 이메일": "email_address", "아웃룩 도메인 메일": "email_address", "아웃룩 도메인 mail": "email_address",
    "핫메일 account email": "email_address", "야후 account email": "email_address", "아웃룩 account email": "email_address",
    "아웃룩 domain email": "email_address", "야후 domain email": "email_address", "핫메일 domain email": "email_address",
    "네이버 domain email": "email_address", "네이버 account mail": "email_address",
         # @로 시작하는 모든 패턴을 email_address로 매핑 (정규표현식 기반 처리)
     "@": "email_address",
     # @로 시작하는 모든 패턴을 email_address로 매핑 (더 구체적인 패턴들)
     "@3920": "email_address", "@abc123": "email_address", "@test": "email_address",
     "@mycompany": "email_address", "@random": "email_address", "@12345": "email_address",
     "@hello": "email_address", "@world": "email_address",
    "야후 account mail": "email_address", "핫메일 account mail": "email_address",
    "아웃룩 account mail": "email_address", "아웃룩 주소": "email_address",
    # 추가 도메인들
    "다음 도메인 이메일": "email_address", "다음 도메인 메일": "email_address", "다음 도메인 mail": "email_address",
    "네이트 도메인 이메일": "email_address", "네이트 도메인 메일": "email_address", "네이트 도메인 mail": "email_address",
    "한메일 도메인 이메일": "email_address", "한메일 도메인 메일": "email_address", "한메일 도메인 mail": "email_address",
    "아이클라우드 도메인 이메일": "email_address", "아이클라우드 도메인 메일": "email_address", "아이클라우드 도메인 mail": "email_address",
    "프로톤메일 도메인 이메일": "email_address", "프로톤메일 도메인 메일": "email_address", "프로톤메일 도메인 mail": "email_address",
    # 학교 메일 도메인들
    "세종대 메일": "email_address", "세종대 이메일": "email_address", "세종대 계정 이메일": "email_address",
    "서울대 메일": "email_address", "서울대 이메일": "email_address", "서울대 계정 이메일": "email_address",
    "고려대 메일": "email_address", "고려대 이메일": "email_address", "고려대 계정 이메일": "email_address",
    "연세대 메일": "email_address", "연세대 이메일": "email_address", "연세대 계정 이메일": "email_address",
    "카이스트 메일": "email_address", "카이스트 이메일": "email_address", "카이스트 계정 이메일": "email_address",
    "포항공대 메일": "email_address", "포항공대 이메일": "email_address", "포항공대 계정 이메일": "email_address",
    "경희대 메일": "email_address", "경희대 이메일": "email_address", "경희대 계정 이메일": "email_address",
    "한양대 메일": "email_address", "한양대 이메일": "email_address", "한양대 계정 이메일": "email_address",
    "이화여대 메일": "email_address", "이화여대 이메일": "email_address", "이화여대 계정 이메일": "email_address",
    "인하대 메일": "email_address", "인하대 이메일": "email_address", "인하대 계정 이메일": "email_address",
    "부산대 메일": "email_address", "부산대 이메일": "email_address", "부산대 계정 이메일": "email_address",
    "경북대 메일": "email_address", "경북대 이메일": "email_address", "경북대 계정 이메일": "email_address",
    "중앙대 메일": "email_address", "중앙대 이메일": "email_address", "중앙대 계정 이메일": "email_address",
    "서강대 메일": "email_address", "서강대 이메일": "email_address", "서강대 계정 이메일": "email_address",
    "국민대 메일": "email_address", "국민대 이메일": "email_address", "국민대 계정 이메일": "email_address",
    "아주대 메일": "email_address", "아주대 이메일": "email_address", "아주대 계정 이메일": "email_address",
    "조선대 메일": "email_address", "조선대 이메일": "email_address", "조선대 계정 이메일": "email_address",
    "계명대 메일": "email_address", "계명대 이메일": "email_address", "계명대 계정 이메일": "email_address",
    "단국대 메일": "email_address", "단국대 이메일": "email_address", "단국대 계정 이메일": "email_address",
    # 학교 메일 도메인들 (학교 포함)
    "세종대학교 메일": "email_address", "세종대학교 이메일": "email_address", "세종대학교 계정 이메일": "email_address",
    "서울대학교 메일": "email_address", "서울대학교 이메일": "email_address", "서울대학교 계정 이메일": "email_address",
    "고려대학교 메일": "email_address", "고려대학교 이메일": "email_address", "고려대학교 계정 이메일": "email_address",
    "연세대학교 메일": "email_address", "연세대학교 이메일": "email_address", "연세대학교 계정 이메일": "email_address",
    "한국과학기술원 메일": "email_address", "한국과학기술원 이메일": "email_address", "한국과학기술원 계정 이메일": "email_address",
    "포항공과대학교 메일": "email_address", "포항공과대학교 이메일": "email_address", "포항공과대학교 계정 이메일": "email_address",
    "경희대학교 메일": "email_address", "경희대학교 이메일": "email_address", "경희대학교 계정 이메일": "email_address",
    "한양대학교 메일": "email_address", "한양대학교 이메일": "email_address", "한양대학교 계정 이메일": "email_address",
    "이화여자대학교 메일": "email_address", "이화여자대학교 이메일": "email_address", "이화여자대학교 계정 이메일": "email_address",
    "인하대학교 메일": "email_address", "인하대학교 이메일": "email_address", "인하대학교 계정 이메일": "email_address",
    "부산대학교 메일": "email_address", "부산대학교 이메일": "email_address", "부산대학교 계정 이메일": "email_address",
    "경북대학교 메일": "email_address", "경북대학교 이메일": "email_address", "경북대학교 계정 이메일": "email_address",
    "중앙대학교 메일": "email_address", "중앙대학교 이메일": "email_address", "중앙대학교 계정 이메일": "email_address",
    "서강대학교 메일": "email_address", "서강대학교 이메일": "email_address", "서강대학교 계정 이메일": "email_address",
    "국민대학교 메일": "email_address", "국민대학교 이메일": "email_address", "국민대학교 계정 이메일": "email_address",
    "아주대학교 메일": "email_address", "아주대학교 이메일": "email_address", "아주대학교 계정 이메일": "email_address",
    "조선대학교 메일": "email_address", "조선대학교 이메일": "email_address", "조선대학교 계정 이메일": "email_address",
    "계명대학교 메일": "email_address", "계명대학교 이메일": "email_address", "계명대학교 계정 이메일": "email_address",
    "단국대학교 메일": "email_address", "단국대학교 이메일": "email_address", "단국대학교 계정 이메일": "email_address",
    "naver.com으로요": "email_address", "gmail.com으로요": "email_address", "yahoo.com으로요": "email_address", "hotmail.com으로요": "email_address", "outlook.com으로요": "email_address", "sju.com으로요": "email_address",
    "daum.net으로요": "email_address", "nate.com으로요": "email_address", "hanmail.net으로요": "email_address", "icloud.com으로요": "email_address", "protonmail.com으로요": "email_address",
    "sejong.ac.kr으로요": "email_address", "snu.ac.kr으로요": "email_address", "korea.ac.kr으로요": "email_address", "yonsei.ac.kr으로요": "email_address", "kaist.ac.kr으로요": "email_address",
    "postech.ac.kr으로요": "email_address", "khu.ac.kr으로요": "email_address", "hanyang.ac.kr으로요": "email_address", "ewha.ac.kr으로요": "email_address", "inha.ac.kr으로요": "email_address",
    "pusan.ac.kr으로요": "email_address", "knu.ac.kr으로요": "email_address", "cau.ac.kr으로요": "email_address", "sogang.ac.kr으로요": "email_address", "kookmin.ac.kr으로요": "email_address",
    "ajou.ac.kr으로요": "email_address", "chosun.ac.kr으로요": "email_address", "kmu.ac.kr으로요": "email_address", "dankook.ac.kr으로요": "email_address",
    # 도메인만으로도 이메일 인식
    "naver.com": "email_address", "gmail.com": "email_address", "yahoo.com": "email_address", "hotmail.com": "email_address", "outlook.com": "email_address",
    "daum.net": "email_address", "nate.com": "email_address", "hanmail.net": "email_address", "icloud.com": "email_address", "protonmail.com": "email_address",
    "sejong.ac.kr": "email_address", "snu.ac.kr": "email_address", "korea.ac.kr": "email_address", "yonsei.ac.kr": "email_address", "kaist.ac.kr": "email_address",
    "postech.ac.kr": "email_address", "khu.ac.kr": "email_address", "hanyang.ac.kr": "email_address", "ewha.ac.kr": "email_address", "inha.ac.kr": "email_address",
    "pusan.ac.kr": "email_address", "knu.ac.kr": "email_address", "cau.ac.kr": "email_address", "sogang.ac.kr": "email_address", "kookmin.ac.kr": "email_address",
    "ajou.ac.kr": "email_address", "chosun.ac.kr": "email_address", "kmu.ac.kr": "email_address", "dankook.ac.kr": "email_address",
    # @ 패턴 추가 (am.dk형, am.dk 등)
    "@am.dk형": "email_address", "@am.dk": "email_address", "@am.dk.com": "email_address", "@am.dk.net": "email_address",
    "@test.com": "email_address", "@example.com": "email_address", "@sample.com": "email_address",
    "@company.com": "email_address", "@business.com": "email_address", "@corp.com": "email_address",
    "@org.com": "email_address", "@edu.com": "email_address", "@gov.com": "email_address",
    "Naver email": "email_address", "Naver account email": "email_address", "Naver mail address": "email_address",
    "Naver email address": "email_address", "Naver domain email": "email_address", "Naver account mail": "email_address",
    "Naver ID email": "email_address", "Naver domain mail": "email_address",
    "Gmail email": "email_address", "Gmail account email": "email_address", "Gmail mail address": "email_address",
    "Gmail email address": "email_address", "Gmail domain email": "email_address", "Gmail account mail": "email_address",
    "Gmail ID email": "email_address", "Gmail domain mail": "email_address",
    "Yahoo email": "email_address", "Yahoo account email": "email_address", "Yahoo mail address": "email_address",
    "Yahoo email address": "email_address", "Yahoo domain email": "email_address", "Yahoo account mail": "email_address",
    "Yahoo ID email": "email_address", "Yahoo domain mail": "email_address",
    "Hotmail email": "email_address", "Hotmail account email": "email_address", "Hotmail mail address": "email_address",
    "Hotmail email address": "email_address", "Hotmail domain email": "email_address", "Hotmail account mail": "email_address",
    "Hotmail ID email": "email_address", "Hotmail domain mail": "email_address",
    "Outlook email": "email_address", "Outlook account email": "email_address", "Outlook mail address": "email_address",
    "Outlook email address": "email_address", "Outlook domain email": "email_address", "Outlook account mail": "email_address",
    "Outlook ID email": "email_address", "Outlook domain mail": "email_address",
    "도메인": "domain_name", "도메인 이름": "domain_name",
    "URL": "url", "주소(URL)": "url", "링크": "url", "웹주소": "url",
    "MAC 주소": "mac_address",
    "IPv4 주소": "ip_v4_address",
    "IPv6 주소": "ip_v6_address",
    "유저 에이전트": "user_agent",
    "아바타": "avatar", "프로필 사진": "avatar", "프로필 이미지": "avatar",
    "프로필 그림": "avatar", "프로필 아이콘": "avatar", "프로필 그림 파일": "avatar",
    "프로필 캐릭터": "avatar", "프로필 사진 파일": "avatar", "프로필 얼굴": "avatar",
    "캐릭터 이미지": "avatar", "캐릭터 그림": "avatar", "캐릭터 아이콘": "avatar",
    "사용자 아이콘": "avatar", "사용자 이미지": "avatar", "사용자 사진": "avatar",
    "계정 아이콘": "avatar", "계정 이미지": "avatar", "계정 사진": "avatar",
    "계정 프로필": "avatar", "아바타 이미지": "avatar", "아바타 사진": "avatar",
    "아바타 이미지 파일": "avatar", "프로필 avatar": "avatar", "캐릭터 avatar": "avatar",
    "유저 avatar": "avatar", "계정 avatar": "avatar",
    "PNG": "avatar", "JPG": "avatar", "JPEG": "avatar", "BMP": "avatar",
    "이미지": "avatar", "사진": "avatar", "그림": "avatar",
    "픽셀": "avatar", "해상도": "avatar", "크기": "avatar", "사이즈": "avatar",
    "가로": "avatar", "세로": "avatar", "저장": "avatar", "이미지 형식": "avatar",
    "앱 이름": "app_name", "어플 이름": "app_name",
    "버전": "app_version", "앱 버전": "app_version",
    "기기 모델": "device_model",
    "기기 브랜드": "device_brand",
    "OS": "device_os", "운영체제": "device_os",
    "카드번호": "credit_card_number", "신용카드 번호": "credit_card_number",
    "카드 종류": "credit_card_type", "카드 타입": "credit_card_type", "VISA MASTER 종류": "credit_card_type",
    "통화": "currency", "화폐 단위": "currency",
    "IBAN": "iban", "IBAN 코드": "iban",
    "SWIFT": "swift_bic", "SWIFT 코드": "swift_bic",
    "문단": "paragraphs", "단락": "paragraphs", "설명 글": "paragraphs",
    "날짜": "datetime", "일시": "datetime", "시작": "datetime", "종료": "datetime", 
    "시작일": "datetime", "종료일": "datetime", "from": "datetime", "to": "datetime", 
    "until": "datetime", "부터": "datetime", "까지": "datetime", "포맷": "datetime",
    "조회기간": "datetime", "유효기간": "datetime", "보고서 기간": "datetime", "기간(포함)": "datetime",
    "시작": "datetime", "종료": "datetime", "기준일": "datetime", "기준일 이후": "datetime",
    "형식": "datetime", "format": "datetime", "2023": "datetime", "2024": "datetime", "yyyy": "datetime", "23": "datetime", "24": "datetime",
    "mm": "datetime", "dd": "datetime", "날짜 형식": "datetime", "date format": "datetime",
    "prefer": "datetime", "default": "datetime", "mdy": "datetime", "ymd": "datetime", "dmy": "datetime",
    "일/월/년": "datetime", "년/월/일": "datetime", "월/일/년": "datetime",
    "d/m/yyyy": "datetime", "dd/mm/yyyy": "datetime", "mm/dd/yyyy": "datetime", "yyyy-mm-dd": "datetime",
    "m/d/yyyy": "datetime",
    "기간": "datetime", "년-월-일": "datetime", "방식": "datetime", "range": "datetime",
    "시간": "time",
    "위도": "latitude",
    "경도": "longitude",
    "숫자": "number", "1과 100 사이 숫자": "number", "1~100 숫자": "number",
    # 나이 관련 키워드 추가
    "나이": "number", "연령": "number", "연령대": "number",
    "나이대": "number", "세": "number", "살": "number",
    # 금액/가격 관련 키워드
    "가격": "number", "금액": "number", "결제금액": "number",
    "최소결제금액": "number", "최소 결제금액": "number",
    "price": "number", "amount": "number", "payment": "number",
    "minimum payment": "number", "minimum amount": "number", "minimum": "number",
    "원": "number", "달러": "number", "USD": "number",
    "EUR": "number", "€": "number", "￥": "number", "£": "number",
    # 수량/개수 관련 키워드
    "수량": "number", "개수": "number", "참가자": "number",
    "quantity": "number", "count": "number", "participants": "number",
    "items": "number", "개": "number", "명": "number",
    # 길이/거리 관련 키워드
    "길이": "number", "거리": "number", "폭": "number",
    "length": "number", "distance": "number", "width": "number",
    "cm": "number", "m": "number", "km": "number",
    "inch": "number", "ft": "number", "meters": "number",
    # 무게/질량 관련 키워드
    "무게": "number", "질량": "number",
    "weight": "number", "mass": "number",
    "kg": "number", "g": "number", "ton": "number",
    "lb": "number", "oz": "number", "grams": "number",
    # 온도 관련 키워드
    "온도": "number", "섭씨": "number",
    "temperature": "number", "celsius": "number",
    "℃": "number", "℉": "number", "도": "number",
    # 속도 관련 키워드
    "속도": "number", "주행속도": "number",
    "speed": "number", "driving speed": "number",
    "km/h": "number", "mph": "number",
    # 시간/기간 관련 키워드
    "시간": "number", "분": "number",
    "time": "number", "duration": "number", "minutes": "number",
    "hours": "number", "days": "number", "주": "number",
    "월": "number", "년": "number", "초": "number",
    # 퍼센트/비율 관련 키워드
    "성공률": "number", "확률": "number", "퍼센트": "number",
    "success rate": "number", "probability": "number", "percentage": "number",
    "%": "number", "비율": "number", "ratio": "number",
    # 등급/점수 관련 키워드
    "점수": "number", "등급": "number", "평점": "number",
    "score": "number", "grade": "number", "rating": "number",
    "점": "number", "등급": "number",
}

KOR_TO_ENG_VALUE = {
    # state
    "서울": "Seoul", "도쿄": "Tokyo", "베이징": "Beijing", "뉴욕": "New York", "파리": "Île-de-France",
    "상파울루": "São Paulo", "마드리드": "Madrid", "모스크바": "Moscow", "이슬람불": "Istanbul",
    "바이에른": "Bavaria (Bayern)", "마하라슈트라": "Maharashtra", "온타리오": "Ontario",
    "뉴사우스웨일스": "New South Wales", "잉글랜드": "England", "캘리포니아": "California",
    # country
    "미국": "United States", "중국": "China", "독일": "Germany", "영국": "United Kingdom", "프랑스": "France",
    "일본": "Japan", "인도": "India", "러시아": "Russia", "대한민국": "South Korea", "한국": "South Korea",
    "브라질": "Brazil", "캐나다": "Canada", "이탈리아": "Italy", "호주": "Australia", "스페인": "Spain", "튀르키예": "Turkey",
    # card
    "비자카드": "Visa", "마스터카드": "Mastercard", "아멕스카드": "American Express", "JCB카드": "JCB",
    "유니온페이": "China UnionPay", "마에스트로": "Maestro", "다이너스클럽": "Diners Club International",
    "아메리칸 익스프레스": "American Express", "아멕스": "Amex",
}

EN_TO_TYPE_FIELD = {
    "korean_full_name": "korean_full_name",
    "full name": "full_name", "fullname": "full_name", "name": "full_name",
    "first name": "first_name", "given name": "first_name",
    "last name": "last_name", "surname": "last_name", "family name": "last_name",
    # 영어 전용 표현 (성씨도 로마자 표기)
    "last name is": "last_name", "family name is": "last_name", "surname is": "last_name",
    "whose last name is": "last_name", "whose family name is": "last_name", "whose surname is": "last_name",
    "person whose last name is": "last_name", "person whose surname is": "last_name",
    "users with last name": "last_name", "people with surname": "last_name",
    "having last name": "last_name", "having family name": "last_name",
    "last name equal to": "last_name", "surname equal to": "last_name",
    "as last name": "last_name", "as family name": "last_name",
    "phone": "phone", "phone number": "phone",
    "address": "address", "full address": "address",
    "street address": "street_address", "road address": "street_address",
    "city": "city",
    "state": "state", "province": "state", "region": "state",
    "country": "country", "nation": "country",
    "postal code": "postal_code", "zip code": "postal_code",
    "company name": "company_name", "company": "company_name",
    "job title": "job_title", "position": "job_title",
    "department": "department_corporate", "corporate department": "department_corporate",
    "retail department": "department_retail",
    "product name": "product_name",
    "product category": "product_category",
    "catch phrase": "catch_phrase", "slogan": "catch_phrase",
    "product description": "product_description",
    "language": "language", "color": "color",
    "username": "username", "user name": "username",
    "password": "password",
    "email": "email_address", "email address": "email_address",
    "naver email": "email_address", "naver account email": "email_address", "naver mail address": "email_address",
    "naver email address": "email_address", "naver domain email": "email_address", "naver account mail": "email_address",
    "naver id email": "email_address", "naver domain mail": "email_address",
    "gmail email": "email_address", "gmail account email": "email_address", "gmail mail address": "email_address",
    "gmail email address": "email_address", "gmail domain email": "email_address", "gmail account mail": "email_address",
    "gmail id email": "email_address", "gmail domain mail": "email_address",
    "yahoo email": "email_address", "yahoo account email": "email_address", "yahoo mail address": "email_address",
    "yahoo email address": "email_address", "yahoo domain email": "email_address", "yahoo account mail": "email_address",
    "yahoo id email": "email_address", "yahoo domain mail": "email_address",
    "hotmail email": "email_address", "hotmail account email": "email_address", "hotmail mail address": "email_address",
    "hotmail email address": "email_address", "hotmail domain email": "email_address", "hotmail account mail": "email_address",
    "hotmail id email": "email_address", "hotmail domain mail": "email_address",
    "outlook email": "email_address", "outlook account email": "email_address", "outlook mail address": "email_address",
    "outlook email address": "email_address", "outlook domain email": "email_address", "outlook account mail": "email_address",
    "outlook id email": "email_address", "outlook domain mail": "email_address",
    # 추가 도메인들
    "daum email": "email_address", "daum account email": "email_address", "daum mail address": "email_address",
    "daum email address": "email_address", "daum domain email": "email_address", "daum account mail": "email_address",
    "daum id email": "email_address", "daum domain mail": "email_address",
    "nate email": "email_address", "nate account email": "email_address", "nate mail address": "email_address",
    "nate email address": "email_address", "nate domain email": "email_address", "nate account mail": "email_address",
    "nate id email": "email_address", "nate domain mail": "email_address",
    "hanmail email": "email_address", "hanmail account email": "email_address", "hanmail mail address": "email_address",
    "hanmail email address": "email_address", "hanmail domain email": "email_address", "hanmail account mail": "email_address",
    "hanmail id email": "email_address", "hanmail domain mail": "email_address",
    "icloud email": "email_address", "icloud account email": "email_address", "icloud mail address": "email_address",
    "icloud email address": "email_address", "icloud domain email": "email_address", "icloud account mail": "email_address",
    "icloud id email": "email_address", "icloud domain mail": "email_address",
    "protonmail email": "email_address", "protonmail account email": "email_address", "protonmail mail address": "email_address",
    "protonmail email address": "email_address", "protonmail domain email": "email_address", "protonmail account mail": "email_address",
    "protonmail id email": "email_address", "protonmail domain mail": "email_address",
    "to naver.com": "email_address", "to gmail.com": "email_address", "to yahoo.com": "email_address", "to hotmail.com": "email_address", "to outlook.com": "email_address", "to sju.com": "email_address",
    "to daum.net": "email_address", "to nate.com": "email_address", "to hanmail.net": "email_address", "to icloud.com": "email_address", "to protonmail.com": "email_address",
    "to sejong.ac.kr": "email_address", "to snu.ac.kr": "email_address", "to korea.ac.kr": "email_address", "to yonsei.ac.kr": "email_address", "to kaist.ac.kr": "email_address",
    "to postech.ac.kr": "email_address", "to khu.ac.kr": "email_address", "to hanyang.ac.kr": "email_address", "to ewha.ac.kr": "email_address", "to inha.ac.kr": "email_address",
    "to pusan.ac.kr": "email_address", "to knu.ac.kr": "email_address", "to cau.ac.kr": "email_address", "to sogang.ac.kr": "email_address", "to kookmin.ac.kr": "email_address",
    "to ajou.ac.kr": "email_address", "to chosun.ac.kr": "email_address", "to kmu.ac.kr": "email_address", "to dankook.ac.kr": "email_address",
    "Using your Naver account email, please.": "email_address",
    "To your Naver mail address, please.": "email_address",
    "Using your Naver email address, please.": "email_address",
    "To the email you use for your Naver account, please.": "email_address",
    "Using your Naver account mail, please.": "email_address",
    "Using your Naver domain mail, please.": "email_address",
    "Using your Gmail account email, please.": "email_address",
    "To your Gmail mail address, please.": "email_address",
    "Using your Gmail email address, please.": "email_address",
    "To the email you use for your Gmail account, please.": "email_address",
    "Using your Yahoo account email, please.": "email_address",
    "To your Yahoo mail address, please.": "email_address",
    "Using your Yahoo email address, please.": "email_address",
    "To the email you use for your Yahoo account, please.": "email_address",
    "Using your Hotmail account email, please.": "email_address",
    "To your Hotmail mail address, please.": "email_address",
    "Using your Hotmail email address, please.": "email_address",
    "To the email you use for your Hotmail account, please.": "email_address",
    "Using your Outlook account email, please.": "email_address",
    "To your Outlook mail address, please.": "email_address",
    "Using your Outlook email address, please.": "email_address",
    "To the email you use for your Outlook account, please.": "email_address",
    # 추가 도메인 긴 패턴들
    "Using your Daum account email, please.": "email_address",
    "To your Daum mail address, please.": "email_address",
    "Using your Daum email address, please.": "email_address",
    "To the email you use for your Daum account, please.": "email_address",
    "Using your Nate account email, please.": "email_address",
    "To your Nate mail address, please.": "email_address",
    "Using your Nate email address, please.": "email_address",
    "To the email you use for your Nate account, please.": "email_address",
    "Using your Hanmail account email, please.": "email_address",
    "To your Hanmail mail address, please.": "email_address",
    "Using your Hanmail email address, please.": "email_address",
    "To the email you use for your Hanmail account, please.": "email_address",
    "Using your iCloud account email, please.": "email_address",
    "To your iCloud mail address, please.": "email_address",
    "Using your iCloud email address, please.": "email_address",
    "To the email you use for your iCloud account, please.": "email_address",
    "Using your ProtonMail account email, please.": "email_address",
    "To your ProtonMail mail address, please.": "email_address",
    "Using your ProtonMail email address, please.": "email_address",
    "To the email you use for your ProtonMail account, please.": "email_address",
    # @도메인형 패턴 매핑 (임의의 도메인 지원) - 높은 우선순위
    "@am.dk email": "email_address", "@am.dk email format": "email_address", "@am.dk address": "email_address",
    "@am.dk format": "email_address", "@am.dk domain email": "email_address", "@am.dk account email": "email_address",
    "make it in @am.dk email format": "email_address", "please use an email with @am.dk": "email_address",
    "i need it as an @am.dk address": "email_address", "with an @am.dk email, please": "email_address",
    "using @am.dk domain email, please": "email_address", "please make it an @am.dk account email": "email_address",
    "set it to @am.dk format": "email_address", "use @am.dk only": "email_address",
    "Set it to @am.dk형 format으로요": "email_address", "Set it to @am.dk형 format으로": "email_address",
    "please send it from @am.dk": "email_address", "please write it with @am.dk": "email_address",
    # 일반적인 @도메인형 패턴 (정규표현식으로 처리)
    "@domain email": "email_address", "@domain email format": "email_address", "@domain address": "email_address",
    "@domain format": "email_address", "@domain domain email": "email_address", "@domain account email": "email_address",
    "make it in @domain email format": "email_address", "please use an email with @domain": "email_address",
    "i need it as an @domain address": "email_address", "with an @domain email, please": "email_address",
    "using @domain domain email, please": "email_address", "please make it an @domain account email": "email_address",
    "set it to @domain format": "email_address", "use @domain only": "email_address",
    "Set it to @domain형 format으로요": "email_address", "Set it to @domain형 format으로": "email_address",
    "please send it from @domain": "email_address", "please write it with @domain": "email_address",
    "domain name": "domain_name",
    "url": "url", "link": "url", "website": "url",
    "mac address": "mac_address",
    "ipv4 address": "ip_v4_address",
    "ipv6 address": "ip_v6_address",
    "user agent": "user_agent",
    "avatar": "avatar", "profile image": "avatar",
    "profile picture": "avatar", "profile pic": "avatar", "profile photo": "avatar",
    "profile icon": "avatar", "profile graphic": "avatar", "profile figure": "avatar",
    "profile character": "avatar", "user icon": "avatar", "user image": "avatar",
    "user photo": "avatar", "account icon": "avatar", "account image": "avatar",
    "account picture": "avatar", "character image": "avatar", "character icon": "avatar",
    "character graphic": "avatar", "profile thumbnail": "avatar", "profile portrait": "avatar",
    "avatar image": "avatar", "avatar picture": "avatar", "avatar photo": "avatar",
    "avatar icon": "avatar", "avatar image file": "avatar", "avatar jpg": "avatar",
    "avatar png": "avatar", "profile avatar": "avatar", "profile picture": "avatar",
    "profile photo": "avatar", "character avatar": "avatar", "character image": "avatar",
    "user avatar": "avatar", "user image": "avatar", "account avatar": "avatar",
    "account image": "avatar",
    # 이미지 형식 관련 영어 키워드들
    "png": "avatar", "jpg": "avatar", "jpeg": "avatar", "bmp": "avatar",
    "image": "avatar", "picture": "avatar", "photo": "avatar", 
    "pixel": "avatar", "resolution": "avatar", "size": "avatar",
    "width": "avatar", "height": "avatar", "save": "avatar", "이미지 형식": "avatar", "image format": "avatar",
    "app name": "app_name", "app version": "app_version",
    "device model": "device_model", "device brand": "device_brand",
    "device os": "device_os", "os": "device_os",
    "credit card number": "credit_card_number",
    "credit card type": "credit_card_type",
    "product price": "product_price",
    "currency": "currency",
    "iban": "iban",
    "swift bic": "swift_bic",
    "paragraph": "paragraphs", "paragraphs": "paragraphs",
    "datetime": "datetime", "date": "datetime", "from": "datetime", "to": "datetime",
    "until": "datetime", "start": "datetime", "end": "datetime", "format": "datetime", "2023": "datetime", "23": "datetime", "24": "datetime",
    "through": "datetime", "on or after": "datetime", "on or before": "datetime",
    "2024": "datetime", "yyyy": "datetime", "mm": "datetime", "dd": "datetime",
    "date format": "datetime", "prefer": "datetime", "default": "datetime", "mdy": "datetime", 
    "ymd": "datetime", "dmy": "datetime", "DMY": "datetime", "day/month/year": "datetime",
    "d/m/yyyy": "datetime", "dd/mm/yyyy": "datetime", "mm/dd/yyyy": "datetime", "yyyy-mm-dd": "datetime",
    "m/d/yyyy": "datetime",
    "yyyy-mm": "datetime", "ISO 8601": "datetime", "ISO": "datetime",
    "range": "datetime", "use": "datetime", "please use": "datetime",
    "time": "time",
    "latitude": "latitude", "longitude": "longitude",
    "number": "number", "number between 1 and 100": "number",
    # 나이 관련 영어 키워드 추가
    "age": "number", "years old": "number", "year old": "number",
    "years": "number", "year": "number", "minimum age": "number",
    "maximum age": "number", "exact age": "number",
    # 금액/가격 관련 키워드
    "price": "number", "amount": "number", "payment": "number",
    "minimum payment": "number", "minimum amount": "number", "minimum": "number",
    "minimum payment is": "number", "minimum amount is": "number",
    "USD": "number", "EUR": "number", "dollars": "number",
    # 수량/개수 관련 키워드
    "quantity": "number", "count": "number", "participants": "number",
    "items": "number", "order": "number",
    # 길이/거리 관련 키워드
    "length": "number", "distance": "number", "width": "number",
    "cm": "number", "m": "number", "km": "number",
    "inch": "number", "ft": "number", "meters": "number",
    # 무게/질량 관련 키워드
    "weight": "number", "mass": "number",
    "kg": "number", "g": "number", "ton": "number",
    "lb": "number", "oz": "number", "grams": "number",
    # 온도 관련 키워드
    "temperature": "number", "celsius": "number",
    "℃": "number", "℉": "number",
    # 속도 관련 키워드
    "speed": "number", "driving speed": "number",
    "km/h": "number", "mph": "number",
    # 시간/기간 관련 키워드
    "time": "number", "duration": "number", "minutes": "number",
    "hours": "number", "days": "number", "seconds": "number",
    "weeks": "number", "months": "number", "years": "number",
    # 퍼센트/비율 관련 키워드
    "success rate": "number", "probability": "number", "percentage": "number",
    "ratio": "number",
    # nullable 관련 키워드는 datetime 컨텍스트에서 처리
    "nullable": "datetime",
    # 등급/점수 관련 키워드
    "score": "number", "grade": "number", "rating": "number",
}