from .constraint_parser import Parser

test_cases = [
      # Korean name constraints   73
        "엔샵이라는 성을 가진 사람",
        "성이 제갈인 사람",
        "성이 다혜인 사람",
        "성이 김인 사람",
        "성씨가 이인 사람",
        "성이 박으로 시작하는 사람",
        "성이 최로 시작하는 사람",
        "김 성을 가진 사람",
        "이 성씨를 가진 사람",
        "정 성을 쓰는 사람",
        "강 성씨를 쓰는 사람",
        "성이 윤인 사람",
        "성이 장임",
        "성씨가 임임",
        "성이 황으로 되어 있는 사람 nullable 10%",
        "성씨가 조로 되어 있는 사람",
        "성이 유라는 사람",
        "성씨가 한이라는 사람",
        "성이 오이신 분",
        "성씨가 서이신 분 NULL 5%",
        "성이 신이신 사람",
        "성씨가 권이신 사람",
        "성이 안으로 끝나는 사람 null 5퍼센트",
        "성이 프로그래밍인 사람last name: 윤",
        "family name: 장",
        "full name starts with 유 missing 20%",
        "full name begins with 한",
        "장씨만 있고 nullable이 30이면 좋겠어",
        "다혜씨면 좋겠어",
        "성이 서인 사람이면 좋겠는 걸",
        "성이 서, 결측 20",
        "성이 다혜라는 사람인데 null 값이 10임",
        "김씨인 사람만 만들어줘",
        "이씨만",
        "박씨",
        "최씨인 사람",
        "김씨",
        "이씨인 사람만",
        "박씨만",
        "최씨",
        "김씨인 사람",
        "이씨인 사람만",
        "박씨인 사람",
        "최씨인 사람만",
        "김씨 인 사람",
        "이씨 인 사람만",
        "박씨 인 사람",
        "최씨 인 사람만",
        "김씨로",
        "이씨로만",
        "박씨로",
        "최씨로만",
        "김씨만",
        "이씨만",
        "박씨만",
        "최씨만",
        "김씨 성을 가진 사람",
        "이씨 성을 가진 사람만",
        "박씨 성을 가진 사람",
        "최씨 성을 가진 사람만",
        "김씨 성씨를 가진 사람",
        "이씨 성씨를 가진 사람만",
        "박씨 성씨를 가진 사람",
        "최씨 성씨를 가진 사람만",
        "김씨 null은 10",
        "이씨만 null은 20",
        "박씨 null은 15",
        "최씨인 사람만 null은 5",
        "김씨인 사람만 만들어주고 null은 10",
        "이씨만 null은 20으로",
        "박씨 null은 15이고",
        "최씨인 사람만 null은 5로",
       "korean_full_name lastName 장",

]

parser = Parser()

for i, text in enumerate(test_cases, 1):
    print(f"## 입력: {text}")
    try:
        result = parser.parse_field_constraint(text)
        print(f"{result}")
    except Exception as e:
        print(f"Error: {e}")
    print()