from .constraint_parser import Parser

test_cases = [
      # Paragraphs  90
"문단",
    "단락",
    "글의 문단",
    "본문 단락",
    "글 단락",
    "글의 문단 수",
    "본문 구성 단락",
    "단락 수",
    "문단 수",
    "글의 각 단락",
    "본문의 각 문단",
    "글의 내용 단락",
    "paragraphs",
    "text paragraphs",
    "body paragraphs",
    "content paragraphs",
    "sections",
    "blocks of text",
    "written paragraphs",
    "textual paragraphs",
    "paragraph units",
    "paragraph blocks",
    "each paragraph in the text",
    "문단(paragraph)",
    "단락(paragraph)",
    "본문 문단(body paragraph)",
    "글 단락(text paragraph)",
    "내용 단락(content paragraph)",
    "단락 수(paragraph count)",
    "문단 수(paragraph count)",
    "글의 각 문단(each paragraph)",
    "단락 블록(paragraph block)",
    "글의 문단 구성(paragraph structure)",
    "문단은 최소 3개에서 최대 5개까지 작성해주세요.",
    "3~5개의 문단으로 구성해주세요.",
    "문단 수는 3개 이상 5개 이하로 제한됩니다.",
    "본문은 3개 이상, 5개 이하의 문단을 포함해야 합니다.",
    "문단 개수는 3~5개 범위 내여야 합니다.",
    "문단을 3개 이상 5개 이하로 작성해 주세요.",
    "최소 3개, 최대 5개의 문단을 작성하셔야 합니다.",
    "3개에서 5개 사이의 문단으로 작성 바랍니다.",
    "문단 수는 3~5개로 맞춰주세요.",
    "문단 개수를 3개 이상, 5개 이하로 유지해주세요.",
    "Write between 3 and 5 paragraphs.",
    "Provide no fewer than 3 and no more than 5 paragraphs.",
    "Your text should have from 3 to 5 paragraphs.",
    "Include at least 3 but not more than 5 paragraphs.",
    "The content must be composed of 3–5 paragraphs.",
    "Limit your writing to between 3 and 5 paragraphs.",
    "Your answer should contain a minimum of 3 and a maximum of 5 paragraphs.",
    "Keep the number of paragraphs between three and five.",
    "You should write anywhere from 3 to 5 paragraphs.",
    "The paragraph count should be in the range of 3 to 5.",
    "문단은 3~5개(3 to 5 paragraphs)로 작성해주세요.",
    "최소 3개(at least 3), 최대 5개(no more than 5)의 문단을 작성해야 합니다.",
    "본문은 3개 이상 5개 이하(3–5 paragraphs)로 구성해주세요.",
    "Write between 3 and 5개의 문단.",
    "문단 수를 3~5개(3 to 5) 범위 안으로 맞춰주세요.",
    "At least 3, but no more than 5개의 문단을 포함해주세요.",
    "문단 개수는 3개 이상, 5개 이하(3–5 paragraphs)여야 합니다.",
    "Keep the number of paragraphs between 3 and 5개.",
    "3개 이상 5개 이하의 문단(at least 3, no more than 5)을 작성해주세요.",
    "Your writing should have 3–5개의 문단.",
    "문단을 최소 3개 작성해주세요.",
    "최소 3개의 문단을 포함해 주세요.",
    "3개 이상의 문단으로 작성 바랍니다.",
    "Write at least 3 paragraphs.",
    "Include at least three paragraphs.",
    "Your text must have at least 3 paragraphs.",
    "문단은 최소 3개(at least 3 paragraphs) 작성해주세요.",
    "본문은 최소 3 paragraphs로 작성해야 합니다.",
    "Write at least 3개의 문단.",
    "문단은 최대 3개까지만 작성해주세요.",
    "최대 3개의 문단으로 제한됩니다.",
    "문단 수는 3개 이하로 작성 바랍니다.",
    "Write no more than 3 paragraphs.",
    "Limit your text to a maximum of 3 paragraphs.",
    "You can write up to 3 paragraphs.",
    "문단은 최대 3개(no more than 3 paragraphs)까지 작성 가능합니다.",
    "최대 3 paragraphs까지만 작성해주세요.",
    "Limit to 3개의 문단.",
    "문단은 총 3개로 작성해주세요.",
    "문단 수는 3개로 제한됩니다.",
    "정확히 3개의 문단으로 작성 바랍니다.",
    "Write exactly 3 paragraphs.",
    "Your response must have exactly three paragraphs.",
    "Provide precisely 3 paragraphs.",
    "문단은 정확히 3개(exactly 3 paragraphs)로 작성해주세요.",
    "Exactly 3개의 문단으로 작성해 주세요.",
    "본문은 3 paragraphs로 구성되어야 합니다."
      

]

parser = Parser()

for i, text in enumerate(test_cases, 1):
    print(f"## 입력: {text}")
    try:
        result = parser.parse_field_constraint(text)
        print(f"{result}")
    except Exception as e:
        print(f"Error: {e}")
    print()