services:
  - type: web
    name: ai-synthor
    env: docker
    repo: https://github.com/your-username/synthor.git # 실제 GitHub 저장소 URL로 변경하세요
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production
    healthCheckPath: /
    autoDeploy: true